"""
Django settings for hotel project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-scy&rbo@0%)nvm-^-u(e_3yrxmf(rr*%jt&b6egsyofa#vy+0z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Guest',
    'hotal_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use the SQLite backend
        'NAME': BASE_DIR / 'db.sqlite3',  # Path to the SQLite database file
    }
}





#AUTH_USER_MODEL = 'Guest.User'  # 'app_name.ModelName'




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Title and branding
    "site_title": "Hotel Hidden Paradise Admin",
    "site_header": "HHP Management",
    "site_brand": "🏨 Hidden Paradise",
    "site_logo": "img/admin_logo.png",
    "welcome_sign": "Welcome to Hotel Hidden Paradise Admin Portal",
    "copyright": "Hotel Hidden Paradise",
    
    # Top menu configuration
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Live Dashboard", "url": "/dashboard", "new_window": True},
        {"name": "Bookings", "url": "admin:reservations_reservation_changelist"},
        {"name": "Rooms", "url": "admin:rooms_room_changelist"},
        {"name": "Guests", "url": "admin:guests_guest_changelist"},
        {"name": "Visit Website", "url": "/", "new_window": True},
    ],
    
    # Sidebar customization
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": ['sessions', 'auth'],
    "order_with_respect_to": [
        "reservations", 
        "rooms", 
        "guests", 
        "services",
        "reports"
    ],
    
    # Custom icons for models
    "icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "reservations.Reservation": "fas fa-calendar-check",
        "rooms.Room": "fas fa-bed",
        "rooms.RoomType": "fas fa-tags",
        "guests.Guest": "fas fa-user-tie",
        "services.Service": "fas fa-concierge-bell",
        "services.ServiceRequest": "fas fa-bell",
        "payments.Payment": "fas fa-credit-card",
        "reports.Report": "fas fa-chart-bar",
        "maintenance.Maintenance": "fas fa-tools",
    },
    
    # UI/UX configurations
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_custom.js",
    "show_ui_builder": True,
    
    # Theme settings
    "theme": "lux",
    "dark_mode_theme": "darkly",
    
    # Form configurations
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "reservations.Reservation": "horizontal_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    # Navigation bar
    "navbar": "navbar-dark navbar-primary",
    "navbar_fixed": True,
    "navbar_small_text": False,
    
    # Sidebar styling
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_legacy_style": False,
    
    # Main content area
    "theme": "lux",
    "dark_mode_theme": "darkly",
    "card_shadow": True,
    "card_border": True,
    "card_border_radius": "0.25rem",
    
    # Button styling
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # Table styling
    "table_striped": True,
    "table_hover": True,
    
    # Additional UI elements
    "actions_sticky_top": True,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "show_ui_builder": True,
    
    # Responsive settings
    "body_small_text": False,
    "footer_small_text": True,
    "sidebar_disable_expand": False,
}