# Generated by Django 4.2.18 on 2025-05-09 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Guest', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('id_proof', models.FileField(blank=True, upload_to='guest_ids/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField(default=0)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('active', 'Checked In'), ('completed', 'Checked Out'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('S', 'Standard'), ('D', 'Deluxe'), ('P', 'Premium Suite')], max_length=1)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GuestProfile',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.room'),
        ),
    ]
